openapi: 3.0.3
info:
  title: Blog
  version: 0.0.1
servers:
 - url: http://127.0.0.1:8000/
   description: Developer server
paths:
  /posts:
    get:
      summary: Get all posts with pagination
      tags:
        - Posts
      operationId: getAllPosts
      responses:
        '200':
          description: Get posts list successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostList'
  /posts/{post_id}:
    get:
      summary: Get post by id
      tags:
        - Posts
      operationId: getPostById
      parameters:
        - name: post_id
          in: path
          required: true
          description: post's id
          schema:
            type: integer
      responses:
        '200':
          description: Get post succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnlyPost'
              
              
              
              
components:
  schemas:
    ListItemPost:
      type: object
      required:
        - id
        - head
        - likes
        - comments
      properties:
        id:
          type: integer
          example: 1
        head:
          type: string
          example: History of automotive industry
        likes:
          type: integer
          example: 23
          description: Amount of likes on the post
        comments:
          type: integer
          example: 4
          description: Amount of comments on the post
    PostList:
      type: array
      items:
        $ref: '#/components/schemas/ListItemPost'
    OnlyPost:
      required:
        - name
        - surname
        - head
        - text
        - comments
      properties:
        name:
          type: string
          example: Jason
          description: Author's name
        surname:
          type: string
          example: Willow
          description: Author's surname
        head:
          type: string
          example: History of automotive industry
        text:
          type: string
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
    Comment:
      required:
        - id
        - post_id
        - user_id
        - text
        - created_at
      properties:
        id:
          type: integer
        post_id:
          type: integer
          description: From which post is this comment
        user_id:
          type: integer
          description: Author's id
        text:
          type: string
        created_at:
          type: string
          format: 2023-01-17T15:00:00:00
      
        
      